# Generated by Django 4.2.1 on 2023-06-03 20:25

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_definition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdefinition',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
